### ISSUE TITLE
Feature: SSM/FSM collection

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-catalogue#77]
Y2 feature possibility:
Should SDK Catalogue store SSM/FSM descriptors?

**Comment by jbonnet** [comment]
@dang03 I think, at least for now, SSMs/FSMs just have a link in the NSD/VNFD...

**Comment by mpeuster** [comment]
@dang03 
@jbonnet is right, the SSMs/FSMs are linked from a small section inside the NSD/VNFD.

This is an example for the SSM section inside the NSD:
```yaml
##
## Some service specific managers.
## image: Specifies the DockerHub URI (user/image name) to fetch the SSM image from.
##
service_specific_managers:
  - id: "ssm1"
    description: "An empty example SSM."
    image: "hadik3r/ssm1"
    options:
      - key: "myKey"
        value: "myValue"

```
